# typed: false
# frozen_string_literal: true

# Generated by the Eolas.Cli Azure DevOps pipeline. Do not edit by hand.
class Eolas < Formula
  desc "Eolas CLI - terminal access to the Eolas platform API"
  homepage "https://github.com/eolas-hq/homebrew-eolas-cli"
  version "0.1.14039"
  url "https://github.com/eolas-hq/homebrew-eolas-cli/releases/download/v0.1.14039/eolas-0.1.14039-osx-arm64.tar.gz"
  sha256 "0ab241148f9b40923b9f21220b718cdd0d3811e15e9be35f306d1deb1439a34d"

  depends_on :macos
  depends_on arch: :arm64

  def install
    bin.install "eolas"
  end

  def caveats
    <<~EOS
      To use the CLI with Claude Code (or other AI agents), install the bundled skill:
        eolas skill install
      Re-run it after upgrading so the skill matches the installed CLI version.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/eolas --version")
  end
end
